version: '3.7'
services:
  mongodb:
     image: mongo
     networks:
       - nw-exploracao-planetaria
     ports:
       - "27017:27017"
     container_name: mongodb
  postgresql:
     container_name: postgres
     image: postgres:latest
     environment:
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: admin
       POSTGRES_DB: planets
     ports:
       - "5432:5432"
     networks:
       - nw-exploracao-planetaria
     restart: unless-stopped
     volumes:
       - ./script:/docker-entrypoint-initdb.d
networks: 
  nw-exploracao-planetaria:
       driver: bridge
