server:
  port: 8087

elasticsearch:
  host: elasticsearch
  port: 9200
  index: probe-collision

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
    health:
      elasticsearch:
        enabled: false