server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

spring:
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgresql:5432/probes
    username: ${SPRING_DATASOURCE_USERNAME:appprobe}
    password: ${SPRING_DATASOURCE_PASSWORD:appprobe}
    initialization-mode: always

springdoc:
  api-docs:
    path: /api-docs

services:
  planet:
    url: http://ms-planet:8080

kafka:
  bootstrapAddress: broker:9092
  topics:
    probe: probe